kind: Pod
apiVersion: v1
metadata:
  name: fluss-v1-7cfcbb9499-qrt5j
  generateName: fluss-v1-7cfcbb9499-
  namespace: demo
  labels:
    app: fluss
    pod-template-hash: 7cfcbb9499
    version: v1
  annotations:
    cni.projectcalico.org/podIP: 10.233.70.153/32
    cni.projectcalico.org/podIPs: 10.233.70.153/32
    kubesphere.io/containerSecrets: '{"fluss":"registry-aliyuncs"}'
spec:
  volumes:
    - name: default-token-v9sm8
      secret:
        secretName: default-token-v9sm8
        defaultMode: 420
  containers:
    - name: fluss
      image: "registry.cn-hangzhou.aliyuncs.com/jerrytang/fluss:v3"
      ports:
        - name: http-80
          containerPort: 80
          protocol: TCP
      env:
        - name: ConnectionStrings__blog
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: connectionString
      resources: { }
      volumeMounts:
        - name: default-token-v9sm8
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: centos7
  securityContext: {}
  imagePullSecrets:
    - name: registry-aliyuncs
  affinity: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true

---
kind: Service
apiVersion: v1
metadata:
  name: fluss
  namespace: demo
  labels:
    app: fluss
    version: v1
  annotations:
    kubesphere.io/creator: project-admin
    kubesphere.io/serviceType: statelessservice
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31109
  selector:
    app: fluss
  clusterIP: 10.233.38.203
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
